from __future__ import annotations

from types import TracebackType
from typing import Any, Generic, TypeVar
from collections.abc import Coroutine

__version__: str

_T = TypeVar("_T")
SupportName = str
VehicleTime = tuple[str, float | int]

class _AsyncSubscription(Generic[_T]):
    def recv(self) -> Coroutine[Any, Any, _T]: ...
    def __aiter__(self) -> _AsyncSubscription[_T]: ...
    def __anext__(self) -> Coroutine[Any, Any, _T]: ...

class _ObservationHandle(Generic[_T]):
    def latest(self) -> _T | None: ...
    def wait(self) -> Coroutine[Any, Any, _T]: ...
    def wait_timeout(self, timeout_secs: float) -> Coroutine[Any, Any, _T]: ...

class SystemStatus:
    Unknown: SystemStatus
    Boot: SystemStatus
    Calibrating: SystemStatus
    Standby: SystemStatus
    Active: SystemStatus
    Critical: SystemStatus
    Emergency: SystemStatus
    Poweroff: SystemStatus

class VehicleType:
    Unknown: VehicleType
    FixedWing: VehicleType
    Vtol: VehicleType
    Quadrotor: VehicleType
    Hexarotor: VehicleType
    Octorotor: VehicleType
    Tricopter: VehicleType
    Helicopter: VehicleType
    Coaxial: VehicleType
    GroundRover: VehicleType
    Submarine: VehicleType
    Generic: VehicleType

class AutopilotType:
    Unknown: AutopilotType
    Generic: AutopilotType
    ArduPilotMega: AutopilotType
    Px4: AutopilotType

class GpsFixType:
    NoFix: GpsFixType
    Fix2d: GpsFixType
    Fix3d: GpsFixType
    Dgps: GpsFixType
    RtkFloat: GpsFixType
    RtkFixed: GpsFixType

class MavSeverity:
    Emergency: MavSeverity
    Alert: MavSeverity
    Critical: MavSeverity
    Error: MavSeverity
    Warning: MavSeverity
    Notice: MavSeverity
    Info: MavSeverity
    Debug: MavSeverity

class MissionType:
    Mission: MissionType
    Fence: MissionType
    Rally: MissionType

class MissionFrame:
    Mission: MissionFrame
    GlobalInt: MissionFrame
    GlobalRelativeAltInt: MissionFrame
    GlobalTerrainAltInt: MissionFrame
    LocalNed: MissionFrame
    Other: MissionFrame

class IssueSeverity:
    Error: IssueSeverity
    Warning: IssueSeverity

class TransferDirection:
    Upload: TransferDirection
    Download: TransferDirection

class TransferPhase:
    Idle: TransferPhase
    RequestCount: TransferPhase
    TransferItems: TransferPhase
    AwaitAck: TransferPhase
    Completed: TransferPhase
    Failed: TransferPhase
    Cancelled: TransferPhase

class ParamTransferPhase:
    Idle: ParamTransferPhase
    Downloading: ParamTransferPhase
    Writing: ParamTransferPhase
    Completed: ParamTransferPhase
    Failed: ParamTransferPhase
    Cancelled: ParamTransferPhase

class ParamType:
    Uint8: ParamType
    Int8: ParamType
    Uint16: ParamType
    Int16: ParamType
    Uint32: ParamType
    Int32: ParamType
    Real32: ParamType

class SyncState:
    Unknown: SyncState
    Current: SyncState
    PossiblyStale: SyncState

class ParamOperationKind:
    DownloadAll: ParamOperationKind
    WriteBatch: ParamOperationKind

class SupportState:
    Unknown: SupportState
    Supported: SupportState
    Unsupported: SupportState

class ModeCatalogSource:
    AvailableModes: ModeCatalogSource
    StaticArduPilotTable: ModeCatalogSource

class CurrentModeSource:
    Heartbeat: CurrentModeSource
    CurrentModeMessage: CurrentModeSource

class SensorHealthState:
    NotPresent: SensorHealthState
    Disabled: SensorHealthState
    Unhealthy: SensorHealthState
    Healthy: SensorHealthState

class MavkitError(Exception): ...

class MissionState:
    @property
    def plan(self) -> MissionPlan | None: ...
    @property
    def current_index(self) -> int | None: ...
    @property
    def current_seq(self) -> int | None: ...
    @property
    def total_items(self) -> int: ...
    @property
    def sync(self) -> SyncState: ...
    @property
    def active_op(self) -> str | None: ...

class VehicleIdentity:
    @property
    def system_id(self) -> int: ...
    @property
    def component_id(self) -> int: ...
    @property
    def autopilot(self) -> AutopilotType: ...
    @property
    def vehicle_type(self) -> VehicleType: ...

class GlobalPosition:
    def __init__(
        self,
        latitude_deg: float,
        longitude_deg: float,
        altitude_msl_m: float,
        relative_alt_m: float,
    ) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_msl_m(self) -> float: ...
    @property
    def relative_alt_m(self) -> float: ...

class EulerAttitude:
    def __init__(self, roll_deg: float, pitch_deg: float, yaw_deg: float) -> None: ...
    @property
    def roll_deg(self) -> float: ...
    @property
    def pitch_deg(self) -> float: ...
    @property
    def yaw_deg(self) -> float: ...

class GpsQuality:
    def __init__(
        self,
        fix_type: GpsFixType,
        satellites: int | None,
        hdop: float | None,
    ) -> None: ...
    @property
    def fix_type(self) -> GpsFixType: ...
    @property
    def satellites(self) -> int | None: ...
    @property
    def hdop(self) -> float | None: ...

class CellVoltages:
    def __init__(self, voltages_v: list[float]) -> None: ...
    @property
    def voltages_v(self) -> list[float]: ...

class WaypointProgress:
    def __init__(self, distance_m: float, bearing_deg: float) -> None: ...
    @property
    def distance_m(self) -> float: ...
    @property
    def bearing_deg(self) -> float: ...

class GuidanceState:
    def __init__(self, bearing_deg: float, cross_track_error_m: float) -> None: ...
    @property
    def bearing_deg(self) -> float: ...
    @property
    def cross_track_error_m(self) -> float: ...

class TerrainClearance:
    def __init__(
        self, terrain_height_m: float, height_above_terrain_m: float
    ) -> None: ...
    @property
    def terrain_height_m(self) -> float: ...
    @property
    def height_above_terrain_m(self) -> float: ...

class GeoPoint3dMsl:
    def __init__(
        self, latitude_deg: float, longitude_deg: float, altitude_msl_m: float
    ) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_msl_m(self) -> float: ...

class GeoPoint2d:
    def __init__(self, *, latitude_deg: float, longitude_deg: float) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...

class GeoPoint3dRelHome:
    def __init__(
        self, *, latitude_deg: float, longitude_deg: float, relative_alt_m: float
    ) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def relative_alt_m(self) -> float: ...

class GeoPoint3dTerrain:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_terrain_m: float,
    ) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_terrain_m(self) -> float: ...

class FenceInclusionPolygon:
    def __init__(self, *, vertices: list[GeoPoint2d], inclusion_group: int) -> None: ...
    @property
    def vertices(self) -> list[GeoPoint2d]: ...
    @property
    def inclusion_group(self) -> int: ...

class FenceExclusionPolygon:
    def __init__(self, *, vertices: list[GeoPoint2d]) -> None: ...
    @property
    def vertices(self) -> list[GeoPoint2d]: ...

class FenceInclusionCircle:
    def __init__(
        self, *, center: GeoPoint2d, radius_m: float, inclusion_group: int
    ) -> None: ...
    @property
    def center(self) -> GeoPoint2d: ...
    @property
    def radius_m(self) -> float: ...
    @property
    def inclusion_group(self) -> int: ...

class FenceExclusionCircle:
    def __init__(self, *, center: GeoPoint2d, radius_m: float) -> None: ...
    @property
    def center(self) -> GeoPoint2d: ...
    @property
    def radius_m(self) -> float: ...

class FencePlan:
    def __init__(
        self,
        *,
        return_point: GeoPoint2d | None = None,
        regions: list[
            FenceInclusionPolygon
            | FenceExclusionPolygon
            | FenceInclusionCircle
            | FenceExclusionCircle
        ],
    ) -> None: ...
    @property
    def return_point(self) -> GeoPoint2d | None: ...
    @property
    def regions(
        self,
    ) -> list[
        FenceInclusionPolygon
        | FenceExclusionPolygon
        | FenceInclusionCircle
        | FenceExclusionCircle
    ]: ...

class RallyPlan:
    def __init__(
        self,
        *,
        points: list[GeoPoint3dMsl | GeoPoint3dRelHome | GeoPoint3dTerrain],
    ) -> None: ...
    @property
    def points(self) -> list[GeoPoint3dMsl | GeoPoint3dRelHome | GeoPoint3dTerrain]: ...

class FenceState:
    @property
    def plan(self) -> FencePlan | None: ...
    @property
    def sync(self) -> SyncState: ...
    @property
    def active_op(self) -> str | None: ...

class RallyState:
    @property
    def plan(self) -> RallyPlan | None: ...
    @property
    def sync(self) -> SyncState: ...
    @property
    def active_op(self) -> str | None: ...

class SensorHealthSummary:
    def __init__(
        self,
        *,
        gyro: SensorHealthState,
        accel: SensorHealthState,
        mag: SensorHealthState,
        baro: SensorHealthState,
        gps: SensorHealthState,
        airspeed: SensorHealthState,
        rc_receiver: SensorHealthState,
        battery: SensorHealthState,
        terrain: SensorHealthState,
        geofence: SensorHealthState,
    ) -> None: ...
    @property
    def gyro(self) -> SensorHealthState: ...
    @property
    def accel(self) -> SensorHealthState: ...
    @property
    def mag(self) -> SensorHealthState: ...
    @property
    def baro(self) -> SensorHealthState: ...
    @property
    def gps(self) -> SensorHealthState: ...
    @property
    def airspeed(self) -> SensorHealthState: ...
    @property
    def rc_receiver(self) -> SensorHealthState: ...
    @property
    def battery(self) -> SensorHealthState: ...
    @property
    def terrain(self) -> SensorHealthState: ...
    @property
    def geofence(self) -> SensorHealthState: ...

class StatusTextEvent:
    def __init__(
        self,
        text: str,
        severity: MavSeverity,
        id: int,
        source_system: int,
        source_component: int,
    ) -> None: ...
    @property
    def text(self) -> str: ...
    @property
    def severity(self) -> MavSeverity: ...
    @property
    def id(self) -> int: ...
    @property
    def source_system(self) -> int: ...
    @property
    def source_component(self) -> int: ...

class MetricSample:
    @property
    def value(self) -> Any: ...
    @property
    def source(self) -> str: ...
    @property
    def vehicle_time(self) -> VehicleTime | None: ...
    @property
    def received_at_monotonic_s(self) -> float: ...

class MessageSample:
    @property
    def value(self) -> Any: ...
    @property
    def vehicle_time(self) -> VehicleTime | None: ...
    @property
    def received_at_monotonic_s(self) -> float: ...

class MetricSubscription(_AsyncSubscription[MetricSample]): ...
class MessageSubscription(_AsyncSubscription[MessageSample]): ...

class MetricHandle(_ObservationHandle[MetricSample]):
    def support(self) -> SupportName | None: ...
    def subscribe(self) -> MetricSubscription: ...

class PeriodicMessageHandle(_ObservationHandle[MessageSample]):
    def support(self) -> SupportName | None: ...
    def subscribe(self) -> MessageSubscription: ...
    def request(self, timeout_secs: float) -> Coroutine[Any, Any, MessageSample]: ...
    def set_rate(self, hz: float) -> Coroutine[Any, Any, None]: ...

class EventMessageHandle(_ObservationHandle[MessageSample]):
    def support(self) -> SupportName | None: ...
    def subscribe(self) -> MessageSubscription: ...
    def request(self, timeout_secs: float) -> Coroutine[Any, Any, MessageSample]: ...

class MessageHandle(_ObservationHandle[MessageSample]):
    def support(self) -> SupportName | None: ...
    def subscribe(self) -> MessageSubscription: ...

class TelemetryPositionNamespace:
    def global_pos(self) -> MetricHandle: ...
    def groundspeed_mps(self) -> MetricHandle: ...
    def airspeed_mps(self) -> MetricHandle: ...
    def climb_rate_mps(self) -> MetricHandle: ...
    def heading_deg(self) -> MetricHandle: ...
    def throttle_pct(self) -> MetricHandle: ...

class TelemetryAttitudeNamespace:
    def euler(self) -> MetricHandle: ...

class TelemetryBatteryNamespace:
    def remaining_pct(self) -> MetricHandle: ...
    def voltage_v(self) -> MetricHandle: ...
    def current_a(self) -> MetricHandle: ...
    def energy_consumed_wh(self) -> MetricHandle: ...
    def time_remaining_s(self) -> MetricHandle: ...
    def cells(self) -> MetricHandle: ...

class TelemetryGpsNamespace:
    def quality(self) -> MetricHandle: ...
    def position_msl(self) -> MetricHandle: ...

class TelemetryNavigationNamespace:
    def waypoint(self) -> MetricHandle: ...
    def guidance(self) -> MetricHandle: ...

class TelemetryTerrainNamespace:
    def clearance(self) -> MetricHandle: ...

class TelemetryRcNamespace:
    def channel_pwm_us(self, index: int) -> MetricHandle: ...
    def rssi_pct(self) -> MetricHandle: ...

class TelemetryActuatorsNamespace:
    def servo_pwm_us(self, index: int) -> MetricHandle: ...

class TelemetryMessagesHandle:
    def vfr_hud(self) -> PeriodicMessageHandle: ...
    def global_position_int(self) -> PeriodicMessageHandle: ...
    def local_position_ned(self) -> PeriodicMessageHandle: ...
    def gps_raw_int(self) -> PeriodicMessageHandle: ...
    def attitude(self) -> PeriodicMessageHandle: ...
    def sys_status(self) -> PeriodicMessageHandle: ...
    def battery_status(self, instance: int) -> PeriodicMessageHandle: ...
    def nav_controller_output(self) -> PeriodicMessageHandle: ...
    def terrain_report(self) -> PeriodicMessageHandle: ...
    def rc_channels(self) -> PeriodicMessageHandle: ...
    def servo_output_raw(self, port: int) -> PeriodicMessageHandle: ...
    def home_position(self) -> EventMessageHandle: ...
    def gps_global_origin(self) -> EventMessageHandle: ...
    def status_text(self) -> MessageHandle: ...

class TelemetryHandle:
    def position(self) -> TelemetryPositionNamespace: ...
    def attitude(self) -> TelemetryAttitudeNamespace: ...
    def battery(self) -> TelemetryBatteryNamespace: ...
    def gps(self) -> TelemetryGpsNamespace: ...
    def navigation(self) -> TelemetryNavigationNamespace: ...
    def terrain(self) -> TelemetryTerrainNamespace: ...
    def rc(self) -> TelemetryRcNamespace: ...
    def actuators(self) -> TelemetryActuatorsNamespace: ...
    def messages(self) -> TelemetryMessagesHandle: ...
    def armed(self) -> MetricHandle: ...
    def sensor_health(self) -> MetricHandle: ...
    def home(self) -> MetricHandle: ...
    def origin(self) -> MetricHandle: ...

class SupportStateSubscription(_AsyncSubscription[SupportState]): ...

class SupportStateHandle(_ObservationHandle[SupportState]):
    def subscribe(self) -> SupportStateSubscription: ...

class SupportHandle:
    def command_int(self) -> SupportStateHandle: ...
    def ftp(self) -> SupportStateHandle: ...
    def terrain(self) -> SupportStateHandle: ...
    def mission_fence(self) -> SupportStateHandle: ...
    def mission_rally(self) -> SupportStateHandle: ...
    def ardupilot(self) -> SupportStateHandle: ...

class ModeDescriptor:
    def __init__(
        self,
        *,
        custom_mode: int,
        name: str,
        user_selectable: bool,
        source: ModeCatalogSource,
    ) -> None: ...
    @property
    def custom_mode(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def user_selectable(self) -> bool: ...
    @property
    def source(self) -> ModeCatalogSource: ...

class CurrentMode:
    def __init__(
        self,
        *,
        custom_mode: int,
        name: str,
        intended_custom_mode: int | None = None,
        source: CurrentModeSource,
    ) -> None: ...
    @property
    def custom_mode(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def intended_custom_mode(self) -> int | None: ...
    @property
    def source(self) -> CurrentModeSource: ...

class ModeCatalogSubscription(_AsyncSubscription[list[ModeDescriptor]]): ...

class ModeCatalogHandle(_ObservationHandle[list[ModeDescriptor]]):
    def subscribe(self) -> ModeCatalogSubscription: ...

class CurrentModeSubscription(_AsyncSubscription[CurrentMode]): ...

class CurrentModeHandle(_ObservationHandle[CurrentMode]):
    def subscribe(self) -> CurrentModeSubscription: ...

class ModesHandle:
    def support(self) -> SupportStateHandle: ...
    def catalog(self) -> ModeCatalogHandle: ...
    def current(self) -> CurrentModeHandle: ...

class FirmwareInfo:
    def __init__(
        self,
        *,
        version: str | None = None,
        custom_version: list[int] | None = None,
        git_hash: str | None = None,
        os_version: str | None = None,
    ) -> None: ...
    @property
    def version(self) -> str | None: ...
    @property
    def custom_version(self) -> list[int] | None: ...
    @property
    def git_hash(self) -> str | None: ...
    @property
    def os_version(self) -> str | None: ...

class HardwareInfo:
    def __init__(
        self,
        *,
        board_vendor_id: int | None = None,
        board_product_id: int | None = None,
        usb_vendor_id: int | None = None,
        usb_product_id: int | None = None,
        board_version: int | None = None,
    ) -> None: ...
    @property
    def board_vendor_id(self) -> int | None: ...
    @property
    def board_product_id(self) -> int | None: ...
    @property
    def usb_vendor_id(self) -> int | None: ...
    @property
    def usb_product_id(self) -> int | None: ...
    @property
    def board_version(self) -> int | None: ...

class UniqueIds:
    def __init__(
        self,
        *,
        hardware_uid: list[int] | None = None,
        uid: int | None = None,
        remote_id: str | None = None,
        board_id: str | None = None,
    ) -> None: ...
    @property
    def hardware_uid(self) -> list[int] | None: ...
    @property
    def uid(self) -> int | None: ...
    @property
    def remote_id(self) -> str | None: ...
    @property
    def board_id(self) -> str | None: ...

class PersistentIdentity:
    def __init__(
        self,
        *,
        state: str,
        system_id: int | None = None,
        component_id: int | None = None,
        canonical_id: str | None = None,
        aliases: list[str] | None = None,
    ) -> None: ...
    @property
    def state(self) -> str: ...
    @property
    def system_id(self) -> int | None: ...
    @property
    def component_id(self) -> int | None: ...
    @property
    def canonical_id(self) -> str | None: ...
    @property
    def aliases(self) -> list[str]: ...

class FirmwareInfoSubscription(_AsyncSubscription[FirmwareInfo]): ...

class FirmwareInfoHandle(_ObservationHandle[FirmwareInfo]):
    def subscribe(self) -> FirmwareInfoSubscription: ...

class HardwareInfoSubscription(_AsyncSubscription[HardwareInfo]): ...

class HardwareInfoHandle(_ObservationHandle[HardwareInfo]):
    def subscribe(self) -> HardwareInfoSubscription: ...

class UniqueIdsSubscription(_AsyncSubscription[UniqueIds]): ...

class UniqueIdsHandle(_ObservationHandle[UniqueIds]):
    def subscribe(self) -> UniqueIdsSubscription: ...

class PersistentIdentitySubscription(_AsyncSubscription[PersistentIdentity]): ...

class PersistentIdentityHandle(_ObservationHandle[PersistentIdentity]):
    def subscribe(self) -> PersistentIdentitySubscription: ...

class InfoHandle:
    def firmware(self) -> FirmwareInfoHandle: ...
    def hardware(self) -> HardwareInfoHandle: ...
    def unique_ids(self) -> UniqueIdsHandle: ...
    def best_unique_id(self) -> str | None: ...
    def best_display_id(self) -> str: ...
    def persistent_identity(self) -> PersistentIdentityHandle: ...

class RawMissionCommand:
    def __init__(
        self,
        *,
        command: int,
        frame: MissionFrame,
        x: int = 0,
        y: int = 0,
        z: float = 0.0,
        param1: float = 0.0,
        param2: float = 0.0,
        param3: float = 0.0,
        param4: float = 0.0,
    ) -> None: ...
    @property
    def command(self) -> int: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def z(self) -> float: ...
    @property
    def param1(self) -> float: ...
    @property
    def param2(self) -> float: ...
    @property
    def param3(self) -> float: ...
    @property
    def param4(self) -> float: ...

class GeoPoint3d:
    @staticmethod
    def msl(
        *, latitude_deg: float, longitude_deg: float, altitude_msl_m: float
    ) -> GeoPoint3d: ...
    @staticmethod
    def rel_home(
        *, latitude_deg: float, longitude_deg: float, relative_alt_m: float
    ) -> GeoPoint3d: ...
    @staticmethod
    def terrain(
        *, latitude_deg: float, longitude_deg: float, altitude_terrain_m: float
    ) -> GeoPoint3d: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...

class NavWaypoint:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        hold_time_s: float = 0.0,
        acceptance_radius_m: float = 0.0,
        pass_radius_m: float = 0.0,
        yaw_deg: float = 0.0,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def hold_time_s(self) -> float: ...
    @property
    def acceptance_radius_m(self) -> float: ...
    @property
    def pass_radius_m(self) -> float: ...
    @property
    def yaw_deg(self) -> float: ...
    @staticmethod
    def from_point(
        *,
        position: GeoPoint3d,
        hold_time_s: float = 0.0,
        acceptance_radius_m: float = 0.0,
        pass_radius_m: float = 0.0,
        yaw_deg: float = 0.0,
    ) -> NavWaypoint: ...

class NavTakeoff:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        pitch_deg: float = 0.0,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def pitch_deg(self) -> float: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d, pitch_deg: float = 0.0) -> NavTakeoff: ...

class NavLand:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        abort_alt_m: float = 0.0,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def abort_alt_m(self) -> float: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d, abort_alt_m: float = 0.0) -> NavLand: ...

class NavLoiterTime:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        time_s: float = 0.0,
        direction: str = "clockwise",
        exit_xtrack: bool = False,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def time_s(self) -> float: ...
    @property
    def direction(self) -> str: ...
    @property
    def exit_xtrack(self) -> bool: ...
    @staticmethod
    def from_point(
        *,
        position: GeoPoint3d,
        time_s: float = 0.0,
        direction: str = "clockwise",
        exit_xtrack: bool = False,
    ) -> NavLoiterTime: ...

class NavGuidedEnable:
    def __init__(self, *, enabled: bool) -> None: ...
    @property
    def enabled(self) -> bool: ...

class NavReturnToLaunch:
    def __init__(self) -> None: ...

class NavSplineWaypoint:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        hold_time_s: float = 0.0,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def hold_time_s(self) -> float: ...
    @staticmethod
    def from_point(
        *, position: GeoPoint3d, hold_time_s: float = 0.0
    ) -> NavSplineWaypoint: ...

class NavArcWaypoint:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        arc_angle_deg: float,
        direction: str = "clockwise",
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def arc_angle_deg(self) -> float: ...
    @property
    def direction(self) -> str: ...
    @staticmethod
    def from_point(
        *, position: GeoPoint3d, arc_angle_deg: float, direction: str = "clockwise"
    ) -> NavArcWaypoint: ...

class NavLoiterUnlimited:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        radius_m: float = 0.0,
        direction: str = "clockwise",
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def radius_m(self) -> float: ...
    @property
    def direction(self) -> str: ...
    @staticmethod
    def from_point(
        *, position: GeoPoint3d, radius_m: float = 0.0, direction: str = "clockwise"
    ) -> NavLoiterUnlimited: ...

class NavLoiterTurns:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        turns: float,
        radius_m: float = 0.0,
        direction: str = "clockwise",
        exit_xtrack: bool = False,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def turns(self) -> float: ...
    @property
    def radius_m(self) -> float: ...
    @property
    def direction(self) -> str: ...
    @property
    def exit_xtrack(self) -> bool: ...
    @staticmethod
    def from_point(
        *,
        position: GeoPoint3d,
        turns: float,
        radius_m: float = 0.0,
        direction: str = "clockwise",
        exit_xtrack: bool = False,
    ) -> NavLoiterTurns: ...

class NavLoiterToAlt:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        radius_m: float = 0.0,
        direction: str = "clockwise",
        exit_xtrack: bool = False,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def radius_m(self) -> float: ...
    @property
    def direction(self) -> str: ...
    @property
    def exit_xtrack(self) -> bool: ...
    @staticmethod
    def from_point(
        *,
        position: GeoPoint3d,
        radius_m: float = 0.0,
        direction: str = "clockwise",
        exit_xtrack: bool = False,
    ) -> NavLoiterToAlt: ...

class NavContinueAndChangeAlt:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        action: str = "neutral",
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def action(self) -> str: ...
    @staticmethod
    def from_point(
        *, position: GeoPoint3d, action: str = "neutral"
    ) -> NavContinueAndChangeAlt: ...

class NavDelay:
    def __init__(
        self, *, seconds: float, hour_utc: float, min_utc: float, sec_utc: float
    ) -> None: ...
    @property
    def seconds(self) -> float: ...
    @property
    def hour_utc(self) -> float: ...
    @property
    def min_utc(self) -> float: ...
    @property
    def sec_utc(self) -> float: ...

class NavAltitudeWait:
    def __init__(
        self, *, altitude_m: float, descent_rate_mps: float, wiggle_time_s: float
    ) -> None: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def descent_rate_mps(self) -> float: ...
    @property
    def wiggle_time_s(self) -> float: ...

class NavVtolTakeoff:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d) -> NavVtolTakeoff: ...

class NavVtolLand:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        options: int = 0,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def options(self) -> int: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d, options: int = 0) -> NavVtolLand: ...

class NavPayloadPlace:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        max_descent_m: float = 0.0,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def max_descent_m(self) -> float: ...
    @staticmethod
    def from_point(
        *, position: GeoPoint3d, max_descent_m: float = 0.0
    ) -> NavPayloadPlace: ...

class NavSetYawSpeed:
    def __init__(
        self, *, angle_deg: float, speed_mps: float, relative: bool
    ) -> None: ...
    @property
    def angle_deg(self) -> float: ...
    @property
    def speed_mps(self) -> float: ...
    @property
    def relative(self) -> bool: ...

class NavScriptTime:
    def __init__(
        self,
        *,
        command: int,
        timeout_s: float,
        arg1: float,
        arg2: float,
        arg3: int,
        arg4: int,
    ) -> None: ...
    @property
    def command(self) -> int: ...
    @property
    def timeout_s(self) -> float: ...
    @property
    def arg1(self) -> float: ...
    @property
    def arg2(self) -> float: ...
    @property
    def arg3(self) -> int: ...
    @property
    def arg4(self) -> int: ...

class NavAttitudeTime:
    def __init__(
        self,
        *,
        time_s: float,
        roll_deg: float,
        pitch_deg: float,
        yaw_deg: float,
        climb_rate_mps: float,
    ) -> None: ...
    @property
    def time_s(self) -> float: ...
    @property
    def roll_deg(self) -> float: ...
    @property
    def pitch_deg(self) -> float: ...
    @property
    def yaw_deg(self) -> float: ...
    @property
    def climb_rate_mps(self) -> float: ...

class DoChangeSpeed:
    def __init__(
        self,
        *,
        speed_mps: float,
        throttle_pct: float = 0.0,
        speed_type: str = "groundspeed",
    ) -> None: ...
    @property
    def speed_type(self) -> str: ...
    @property
    def speed_mps(self) -> float: ...
    @property
    def throttle_pct(self) -> float: ...

class DoSetHome:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        use_current: bool = False,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def use_current(self) -> bool: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d, use_current: bool = False) -> DoSetHome: ...

class DoSetRelay:
    def __init__(self, *, number: int, state: bool) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def state(self) -> bool: ...

class DoSetRoiNone:
    def __init__(self) -> None: ...

class DoJump:
    def __init__(self, *, target_index: int, repeat_count: int) -> None: ...
    @property
    def target_index(self) -> int: ...
    @property
    def repeat_count(self) -> int: ...

class DoJumpTag:
    def __init__(self, *, tag: int, repeat_count: int) -> None: ...
    @property
    def tag(self) -> int: ...
    @property
    def repeat_count(self) -> int: ...

class DoTag:
    def __init__(self, *, tag: int) -> None: ...
    @property
    def tag(self) -> int: ...

class DoPauseContinue:
    def __init__(self, *, pause: bool) -> None: ...
    @property
    def pause(self) -> bool: ...

class DoSetReverse:
    def __init__(self, *, reverse: bool) -> None: ...
    @property
    def reverse(self) -> bool: ...

class DoLandStart:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d) -> DoLandStart: ...

class DoReturnPathStart:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d) -> DoReturnPathStart: ...

class DoGoAround:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d) -> DoGoAround: ...

class DoSetRoiLocation:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d) -> DoSetRoiLocation: ...

class DoSetRoi:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float,
        frame: MissionFrame = MissionFrame.GlobalRelativeAltInt,
        mode: int = 0,
    ) -> None: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...
    @property
    def mode(self) -> int: ...
    @staticmethod
    def from_point(*, position: GeoPoint3d, mode: int = 0) -> DoSetRoi: ...

class DoMountControl:
    def __init__(
        self, *, pitch_deg: float, roll_deg: float, yaw_deg: float
    ) -> None: ...
    @property
    def pitch_deg(self) -> float: ...
    @property
    def roll_deg(self) -> float: ...
    @property
    def yaw_deg(self) -> float: ...

class DoGimbalManagerPitchYaw:
    def __init__(
        self,
        *,
        pitch_deg: float,
        yaw_deg: float,
        pitch_rate_dps: float,
        yaw_rate_dps: float,
        flags: int,
        gimbal_id: int,
    ) -> None: ...
    @property
    def pitch_deg(self) -> float: ...
    @property
    def yaw_deg(self) -> float: ...
    @property
    def pitch_rate_dps(self) -> float: ...
    @property
    def yaw_rate_dps(self) -> float: ...
    @property
    def flags(self) -> int: ...
    @property
    def gimbal_id(self) -> int: ...

class DoCamTriggerDistance:
    def __init__(self, *, meters: float, trigger_now: bool) -> None: ...
    @property
    def meters(self) -> float: ...
    @property
    def trigger_now(self) -> bool: ...

class DoDigicamConfigure:
    def __init__(
        self,
        *,
        shooting_mode: int,
        shutter_speed: int,
        aperture: float,
        iso: int,
        exposure_type: int,
        cmd_id: int,
        cutoff_time: float,
    ) -> None: ...
    @property
    def shooting_mode(self) -> int: ...
    @property
    def shutter_speed(self) -> int: ...
    @property
    def aperture(self) -> float: ...
    @property
    def iso(self) -> int: ...
    @property
    def exposure_type(self) -> int: ...
    @property
    def cmd_id(self) -> int: ...
    @property
    def cutoff_time(self) -> float: ...

class DoDigicamControl:
    def __init__(
        self,
        *,
        session: int,
        zoom_pos: int,
        zoom_step: int,
        focus_lock: int,
        shooting_cmd: int,
        cmd_id: int,
    ) -> None: ...
    @property
    def session(self) -> int: ...
    @property
    def zoom_pos(self) -> int: ...
    @property
    def zoom_step(self) -> int: ...
    @property
    def focus_lock(self) -> int: ...
    @property
    def shooting_cmd(self) -> int: ...
    @property
    def cmd_id(self) -> int: ...

class DoFenceEnable:
    def __init__(self, *, action: str) -> None: ...
    @property
    def action(self) -> str: ...

class DoParachute:
    def __init__(self, *, action: str) -> None: ...
    @property
    def action(self) -> str: ...

class DoGripper:
    def __init__(self, *, number: int, action: str) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def action(self) -> str: ...

class DoSprayer:
    def __init__(self, *, enabled: bool) -> None: ...
    @property
    def enabled(self) -> bool: ...

class DoWinch:
    def __init__(
        self,
        *,
        number: int,
        action: str,
        release_length_m: float,
        release_rate_mps: float,
    ) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def action(self) -> str: ...
    @property
    def release_length_m(self) -> float: ...
    @property
    def release_rate_mps(self) -> float: ...

class DoEngineControl:
    def __init__(
        self,
        *,
        start: bool,
        cold_start: bool,
        height_delay_m: float,
        allow_disarmed: bool,
    ) -> None: ...
    @property
    def start(self) -> bool: ...
    @property
    def cold_start(self) -> bool: ...
    @property
    def height_delay_m(self) -> float: ...
    @property
    def allow_disarmed(self) -> bool: ...

class DoInvertedFlight:
    def __init__(self, *, inverted: bool) -> None: ...
    @property
    def inverted(self) -> bool: ...

class DoAutotuneEnable:
    def __init__(self, *, enabled: bool) -> None: ...
    @property
    def enabled(self) -> bool: ...

class DoSetServo:
    def __init__(self, *, channel: int, pwm: int) -> None: ...
    @property
    def channel(self) -> int: ...
    @property
    def pwm(self) -> int: ...

class DoRepeatServo:
    def __init__(
        self, *, channel: int, pwm: int, count: int, cycle_time_s: float
    ) -> None: ...
    @property
    def channel(self) -> int: ...
    @property
    def pwm(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def cycle_time_s(self) -> float: ...

class DoRepeatRelay:
    def __init__(self, *, number: int, count: int, cycle_time_s: float) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def cycle_time_s(self) -> float: ...

class DoSetResumeRepeatDist:
    def __init__(self, *, distance_m: float) -> None: ...
    @property
    def distance_m(self) -> float: ...

class DoAuxFunction:
    def __init__(self, *, function: int, switch_pos: int) -> None: ...
    @property
    def function(self) -> int: ...
    @property
    def switch_pos(self) -> int: ...

class DoSendScriptMessage:
    def __init__(self, *, id: int, p1: float, p2: float, p3: float) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def p1(self) -> float: ...
    @property
    def p2(self) -> float: ...
    @property
    def p3(self) -> float: ...

class DoImageStartCapture:
    def __init__(
        self, *, instance: int, interval_s: float, total_images: int, start_number: int
    ) -> None: ...
    @property
    def instance(self) -> int: ...
    @property
    def interval_s(self) -> float: ...
    @property
    def total_images(self) -> int: ...
    @property
    def start_number(self) -> int: ...

class DoImageStopCapture:
    def __init__(self, *, instance: int) -> None: ...
    @property
    def instance(self) -> int: ...

class DoVideoStartCapture:
    def __init__(self, *, stream_id: int) -> None: ...
    @property
    def stream_id(self) -> int: ...

class DoVideoStopCapture:
    def __init__(self, *, stream_id: int) -> None: ...
    @property
    def stream_id(self) -> int: ...

class DoSetCameraZoom:
    def __init__(self, *, zoom_type: int, zoom_value: float) -> None: ...
    @property
    def zoom_type(self) -> int: ...
    @property
    def zoom_value(self) -> float: ...

class DoSetCameraFocus:
    def __init__(self, *, focus_type: int, focus_value: float) -> None: ...
    @property
    def focus_type(self) -> int: ...
    @property
    def focus_value(self) -> float: ...

class DoSetCameraSource:
    def __init__(self, *, instance: int, primary: int, secondary: int) -> None: ...
    @property
    def instance(self) -> int: ...
    @property
    def primary(self) -> int: ...
    @property
    def secondary(self) -> int: ...

class DoGuidedLimits:
    def __init__(
        self,
        *,
        max_time_s: float,
        min_alt_m: float,
        max_alt_m: float,
        max_horiz_m: float,
    ) -> None: ...
    @property
    def max_time_s(self) -> float: ...
    @property
    def min_alt_m(self) -> float: ...
    @property
    def max_alt_m(self) -> float: ...
    @property
    def max_horiz_m(self) -> float: ...

class DoVtolTransition:
    def __init__(self, *, target_state: int) -> None: ...
    @property
    def target_state(self) -> int: ...

class CondDelay:
    def __init__(self, *, delay_s: float) -> None: ...
    @property
    def delay_s(self) -> float: ...

class CondDistance:
    def __init__(self, *, distance_m: float) -> None: ...
    @property
    def distance_m(self) -> float: ...

class CondYaw:
    def __init__(
        self,
        *,
        angle_deg: float,
        turn_rate_dps: float = 0.0,
        direction: str = "clockwise",
        relative: bool = False,
    ) -> None: ...
    @property
    def angle_deg(self) -> float: ...
    @property
    def turn_rate_dps(self) -> float: ...
    @property
    def direction(self) -> str: ...
    @property
    def relative(self) -> bool: ...

class MissionItem:
    def __init__(
        self,
        *,
        command: (
            NavWaypoint
            | NavTakeoff
            | NavLand
            | NavLoiterTime
            | NavGuidedEnable
            | NavReturnToLaunch
            | NavSplineWaypoint
            | NavArcWaypoint
            | NavLoiterUnlimited
            | NavLoiterTurns
            | NavLoiterToAlt
            | NavContinueAndChangeAlt
            | NavDelay
            | NavAltitudeWait
            | NavVtolTakeoff
            | NavVtolLand
            | NavPayloadPlace
            | NavSetYawSpeed
            | NavScriptTime
            | NavAttitudeTime
            | DoChangeSpeed
            | DoSetHome
            | DoSetRelay
            | DoSetRoiNone
            | DoJump
            | DoJumpTag
            | DoTag
            | DoPauseContinue
            | DoSetReverse
            | DoLandStart
            | DoReturnPathStart
            | DoGoAround
            | DoSetRoiLocation
            | DoSetRoi
            | DoMountControl
            | DoGimbalManagerPitchYaw
            | DoCamTriggerDistance
            | DoDigicamConfigure
            | DoDigicamControl
            | DoFenceEnable
            | DoParachute
            | DoGripper
            | DoSprayer
            | DoWinch
            | DoEngineControl
            | DoInvertedFlight
            | DoAutotuneEnable
            | DoSetServo
            | DoRepeatServo
            | DoRepeatRelay
            | DoSetResumeRepeatDist
            | DoAuxFunction
            | DoSendScriptMessage
            | DoImageStartCapture
            | DoImageStopCapture
            | DoVideoStartCapture
            | DoVideoStopCapture
            | DoSetCameraZoom
            | DoSetCameraFocus
            | DoSetCameraSource
            | DoGuidedLimits
            | DoVtolTransition
            | CondDelay
            | CondDistance
            | CondYaw
            | RawMissionCommand
            | int
        ),
        frame: MissionFrame | None = None,
        x: int = 0,
        y: int = 0,
        z: float = 0.0,
        param1: float = 0.0,
        param2: float = 0.0,
        param3: float = 0.0,
        param4: float = 0.0,
        current: bool = False,
        autocontinue: bool = True,
    ) -> None: ...
    @property
    def command(self) -> int: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def z(self) -> float: ...
    @property
    def param1(self) -> float: ...
    @property
    def param2(self) -> float: ...
    @property
    def param3(self) -> float: ...
    @property
    def param4(self) -> float: ...
    @property
    def current(self) -> bool: ...
    @property
    def autocontinue(self) -> bool: ...

class HomePosition:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float = 0.0,
    ) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...

class MissionPlan:
    def __init__(self, *, items: list[MissionItem]) -> None: ...
    @property
    def items(self) -> list[MissionItem]: ...
    def __len__(self) -> int: ...

class MissionIssue:
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def seq(self) -> int | None: ...
    @property
    def severity(self) -> IssueSeverity: ...

class TransferProgress:
    @property
    def direction(self) -> TransferDirection: ...
    @property
    def mission_type(self) -> MissionType: ...
    @property
    def phase(self) -> TransferPhase: ...
    @property
    def completed_items(self) -> int: ...
    @property
    def total_items(self) -> int: ...
    @property
    def retries_used(self) -> int: ...

class TransferError:
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...

class RetryPolicy:
    def __init__(
        self,
        *,
        request_timeout_ms: int = 1500,
        item_timeout_ms: int = 250,
        max_retries: int = 5,
    ) -> None: ...
    @property
    def request_timeout_ms(self) -> int: ...
    @property
    def item_timeout_ms(self) -> int: ...
    @property
    def max_retries(self) -> int: ...

class CompareTolerance:
    def __init__(
        self,
        *,
        param_epsilon: float = 0.0001,
        altitude_epsilon_m: float = 0.01,
    ) -> None: ...
    @property
    def param_epsilon(self) -> float: ...
    @property
    def altitude_epsilon_m(self) -> float: ...

class Param:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> float: ...
    @property
    def param_type(self) -> ParamType: ...
    @property
    def index(self) -> int: ...

class ParamStore:
    @property
    def expected_count(self) -> int: ...
    def get(self, name: str) -> Param | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Param]: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Param: ...

class ParamProgress:
    @property
    def phase(self) -> ParamTransferPhase: ...
    @property
    def received(self) -> int: ...
    @property
    def expected(self) -> int: ...
    @property
    def expected_count(self) -> int | None: ...
    @property
    def index(self) -> int: ...
    @property
    def total(self) -> int: ...
    @property
    def name(self) -> str | None: ...

class ParamWriteResult:
    @property
    def name(self) -> str: ...
    @property
    def requested_value(self) -> float: ...
    @property
    def confirmed_value(self) -> float: ...
    @property
    def success(self) -> bool: ...

class ParamState:
    @property
    def store(self) -> ParamStore | None: ...
    @property
    def sync(self) -> SyncState: ...
    @property
    def active_op(self) -> ParamOperationKind | None: ...

class ParamStateSubscription(_AsyncSubscription[ParamState]): ...
class ParamProgressSubscription(_AsyncSubscription[ParamProgress]): ...
class MissionStateSubscription(_AsyncSubscription[MissionState]): ...
class FenceStateSubscription(_AsyncSubscription[FenceState]): ...
class RallyStateSubscription(_AsyncSubscription[RallyState]): ...

class MissionOperationProgress:
    @property
    def phase(self) -> str: ...
    @property
    def current(self) -> int: ...
    @property
    def total(self) -> int: ...

class MissionProgressSubscription(_AsyncSubscription[MissionOperationProgress]): ...

class MissionUploadOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, None]: ...

class MissionDownloadOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, MissionPlan]: ...

class MissionClearOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, None]: ...

class MissionVerifyOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, bool]: ...

class FenceUploadOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, None]: ...

class FenceDownloadOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, FencePlan]: ...

class FenceClearOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, None]: ...

class RallyUploadOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, None]: ...

class RallyDownloadOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, RallyPlan]: ...

class RallyClearOp:
    def latest(self) -> MissionOperationProgress | None: ...
    def subscribe(self) -> MissionProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, None]: ...

class ParamDownloadOp:
    def latest(self) -> ParamProgress | None: ...
    def subscribe(self) -> ParamProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, ParamStore]: ...

class ParamWriteBatchOp:
    def latest(self) -> ParamProgress | None: ...
    def subscribe(self) -> ParamProgressSubscription: ...
    def cancel(self) -> None: ...
    def wait(self) -> Coroutine[Any, Any, list[ParamWriteResult]]: ...

class ParamsHandle:
    def latest(self) -> ParamState | None: ...
    def wait(self) -> Coroutine[Any, Any, ParamState]: ...
    def wait_timeout(self, timeout_secs: float) -> Coroutine[Any, Any, ParamState]: ...
    def subscribe(self) -> ParamStateSubscription: ...
    def download_all(self) -> ParamDownloadOp: ...
    def write(
        self, name: str, value: float
    ) -> Coroutine[Any, Any, ParamWriteResult]: ...
    def write_batch(self, batch: list[tuple[str, float]]) -> ParamWriteBatchOp: ...

class VehicleConfig:
    def __init__(
        self,
        *,
        gcs_system_id: int = 255,
        gcs_component_id: int = 190,
        auto_request_home: bool = True,
        command_buffer_size: int = 32,
        connect_timeout_secs: float = 30.0,
        transfer_timeout_secs: float = 30.0,
        retry_policy: RetryPolicy | None = None,
    ) -> None: ...
    @property
    def gcs_system_id(self) -> int: ...
    @property
    def gcs_component_id(self) -> int: ...
    @property
    def auto_request_home(self) -> bool: ...
    @property
    def command_buffer_size(self) -> int: ...
    @property
    def connect_timeout_secs(self) -> float: ...
    @property
    def transfer_timeout_secs(self) -> float: ...
    @property
    def retry_policy(self) -> RetryPolicy: ...

class CommandAck:
    @property
    def command(self) -> int: ...
    @property
    def result(self) -> int: ...
    @property
    def progress(self) -> int | None: ...
    @property
    def result_param2(self) -> int | None: ...

class MissionHandle:
    def latest(self) -> MissionState | None: ...
    def wait(self) -> Coroutine[Any, Any, MissionState]: ...
    def wait_timeout(
        self, timeout_secs: float
    ) -> Coroutine[Any, Any, MissionState]: ...
    def subscribe(self) -> MissionStateSubscription: ...
    def upload(self, plan: MissionPlan) -> MissionUploadOp: ...
    def download(self) -> MissionDownloadOp: ...
    def clear(self) -> MissionClearOp: ...
    def verify(self, plan: MissionPlan) -> MissionVerifyOp: ...
    def set_current(self, index: int) -> Coroutine[Any, Any, None]: ...
    def __repr__(self) -> str: ...

class FenceHandle:
    def support(self) -> SupportStateHandle: ...
    def latest(self) -> FenceState | None: ...
    def wait(self) -> Coroutine[Any, Any, FenceState]: ...
    def subscribe(self) -> FenceStateSubscription: ...
    def upload(self, plan: FencePlan) -> FenceUploadOp: ...
    def download(self) -> FenceDownloadOp: ...
    def clear(self) -> FenceClearOp: ...
    def __repr__(self) -> str: ...

class RallyHandle:
    def support(self) -> SupportStateHandle: ...
    def latest(self) -> RallyState | None: ...
    def wait(self) -> Coroutine[Any, Any, RallyState]: ...
    def subscribe(self) -> RallyStateSubscription: ...
    def upload(self, plan: RallyPlan) -> RallyUploadOp: ...
    def download(self) -> RallyDownloadOp: ...
    def clear(self) -> RallyClearOp: ...
    def __repr__(self) -> str: ...

class RawHandle:
    def subscribe(self) -> RawMessageStream: ...
    def command_long(
        self,
        command: int,
        params: list[float] | tuple[float, float, float, float, float, float, float],
    ) -> Coroutine[Any, Any, CommandAck]: ...
    def command_int(
        self,
        command: int,
        frame: int,
        current: int,
        autocontinue: int,
        params: list[float] | tuple[float, float, float, float],
        x: int,
        y: int,
        z: float,
    ) -> Coroutine[Any, Any, CommandAck]: ...
    def request_message(
        self, message_id: int, timeout_secs: float
    ) -> Coroutine[Any, Any, RawMessage]: ...
    def set_message_interval(
        self, message_id: int, interval_us: int
    ) -> Coroutine[Any, Any, None]: ...
    def send(self, message: RawMessage) -> Coroutine[Any, Any, None]: ...
    def __repr__(self) -> str: ...

class ArduCopterHandle:
    def __repr__(self) -> str: ...

class ArduPlaneVtolHandle:
    def __repr__(self) -> str: ...

class ArduRoverHandle:
    def __repr__(self) -> str: ...

class ArduSubHandle:
    def __repr__(self) -> str: ...

class ArduPlaneHandle:
    def vtol(self) -> ArduPlaneVtolHandle | None: ...

class ArduCopterGuidedHandle:
    def takeoff(self, relative_climb_m: float) -> Coroutine[Any, Any, None]: ...
    def goto(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        relative_alt_m: float,
    ) -> Coroutine[Any, Any, None]: ...
    def goto_msl(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_msl_m: float,
    ) -> Coroutine[Any, Any, None]: ...
    def set_velocity_ned(
        self,
        north_mps: float,
        east_mps: float,
        down_mps: float,
    ) -> Coroutine[Any, Any, None]: ...
    def hold(self) -> Coroutine[Any, Any, None]: ...

class ArduPlaneVtolGuidedHandle:
    def takeoff(self, relative_climb_m: float) -> Coroutine[Any, Any, None]: ...
    def hold(self) -> Coroutine[Any, Any, None]: ...

class ArduPlaneGuidedHandle:
    def reposition(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_msl_m: float,
    ) -> Coroutine[Any, Any, None]: ...
    def reposition_rel_home(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        relative_alt_m: float,
    ) -> Coroutine[Any, Any, None]: ...
    def vtol(self) -> ArduPlaneVtolGuidedHandle | None: ...

class ArduRoverGuidedHandle:
    def drive_to(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
    ) -> Coroutine[Any, Any, None]: ...
    def drive(
        self, forward_mps: float, turn_rate_dps: float
    ) -> Coroutine[Any, Any, None]: ...
    def hold(self) -> Coroutine[Any, Any, None]: ...

class ArduSubGuidedHandle:
    def goto_depth(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        depth_m: float,
    ) -> Coroutine[Any, Any, None]: ...
    def set_velocity_body(
        self,
        forward_mps: float,
        lateral_mps: float,
        vertical_mps: float,
        yaw_rate_dps: float,
    ) -> Coroutine[Any, Any, None]: ...
    def hold(self) -> Coroutine[Any, Any, None]: ...

class ArduGuidedSession:
    def close(self) -> Coroutine[Any, Any, None]: ...
    def copter(self) -> ArduCopterGuidedHandle | None: ...
    def plane(self) -> ArduPlaneGuidedHandle | None: ...
    def rover(self) -> ArduRoverGuidedHandle | None: ...
    def sub(self) -> ArduSubGuidedHandle | None: ...
    def __aenter__(self) -> Coroutine[Any, Any, ArduGuidedSession]: ...
    def __aexit__(
        self,
        _exc_type: type[BaseException] | None = None,
        _exc_val: BaseException | None = None,
        _exc_tb: TracebackType | None = None,
    ) -> Coroutine[Any, Any, bool]: ...

class ArduPilotHandle:
    def copter(self) -> ArduCopterHandle | None: ...
    def plane(self) -> ArduPlaneHandle | None: ...
    def rover(self) -> ArduRoverHandle | None: ...
    def sub(self) -> ArduSubHandle | None: ...
    def guided(self) -> Coroutine[Any, Any, ArduGuidedSession]: ...
    def request_prearm_checks(self) -> Coroutine[Any, Any, None]: ...
    def motor_test(
        self,
        instance: int,
        throttle_pct: float,
        duration_s: int,
    ) -> Coroutine[Any, Any, None]: ...
    def preflight_calibration(
        self,
        gyro: bool,
        accel: bool,
        baro: bool,
        accel_trim: bool,
    ) -> Coroutine[Any, Any, None]: ...
    def start_mag_cal(self, compass_mask: int) -> Coroutine[Any, Any, None]: ...
    def accept_mag_cal(self) -> Coroutine[Any, Any, None]: ...
    def cancel_mag_cal(self) -> Coroutine[Any, Any, None]: ...
    def reboot(self) -> Coroutine[Any, Any, None]: ...
    def reboot_to_bootloader(self) -> Coroutine[Any, Any, None]: ...

class Vehicle:
    @staticmethod
    def connect(address: str) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_udp(bind_addr: str) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_tcp(addr: str) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_serial(port: str, baud: int) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_with_config(
        address: str,
        config: VehicleConfig,
    ) -> Coroutine[Any, Any, Vehicle]: ...
    def telemetry(self) -> TelemetryHandle: ...
    def available_modes(self) -> ModesHandle: ...
    def info(self) -> InfoHandle: ...
    def support(self) -> SupportHandle: ...
    def mission(self) -> MissionHandle: ...
    def fence(self) -> FenceHandle: ...
    def rally(self) -> RallyHandle: ...
    def params(self) -> ParamsHandle: ...
    def raw(self) -> RawHandle: ...
    def ardupilot(self) -> ArduPilotHandle: ...
    def identity(self) -> VehicleIdentity: ...
    def arm(self, force: bool) -> Coroutine[Any, Any, None]: ...
    def disarm(self, force: bool) -> Coroutine[Any, Any, None]: ...
    def set_mode(
        self,
        custom_mode: int,
        wait_for_observation: bool = True,
    ) -> Coroutine[Any, Any, None]: ...
    def set_mode_by_name(
        self,
        name: str,
        wait_for_observation: bool = True,
    ) -> Coroutine[Any, Any, None]: ...
    def set_home(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_msl_m: float,
    ) -> Coroutine[Any, Any, None]: ...
    def set_home_current(self) -> Coroutine[Any, Any, None]: ...
    def set_origin(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_msl_m: float,
    ) -> Coroutine[Any, Any, None]: ...
    def disconnect(self) -> Coroutine[Any, Any, None]: ...
    def __aenter__(self) -> Coroutine[Any, Any, Vehicle]: ...
    def __aexit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: TracebackType | None = None,
    ) -> Coroutine[Any, Any, bool]: ...

# Test-support/dev-only API (available with test-support build feature).
class _TestVehicleHarness:
    def push_command_ack_accepted(self, command: int) -> Coroutine[Any, Any, None]: ...
    def push_global_position_int(self) -> Coroutine[Any, Any, None]: ...
    def push_mission_upload_success(
        self, plan: MissionPlan
    ) -> Coroutine[Any, Any, None]: ...
    def push_mission_download_success(
        self, plan: MissionPlan
    ) -> Coroutine[Any, Any, None]: ...
    def sent_message_count(self) -> int: ...

def _connect_test_vehicle() -> Coroutine[
    Any, Any, tuple[Vehicle, _TestVehicleHarness]
]: ...

class RawMessage:
    def __init__(
        self,
        *,
        message_id: int,
        payload: bytes,
        system_id: int = 1,
        component_id: int = 1,
        sequence: int = 0,
    ) -> None: ...
    @property
    def system_id(self) -> int: ...
    @property
    def component_id(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def message_id(self) -> int: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def message_name(self) -> str: ...
    def message_json(self) -> str: ...

class RawMessageStream(_AsyncSubscription[RawMessage]): ...

class TlogEntry:
    @property
    def timestamp_usec(self) -> int: ...
    @property
    def message_id(self) -> int: ...
    @property
    def message_name(self) -> str: ...
    def message_json(self) -> str: ...

class TlogFile:
    @staticmethod
    def open(path: str) -> Coroutine[Any, Any, TlogFile]: ...
    def entries(self) -> Coroutine[Any, Any, list[TlogEntry]]: ...
    def seek_to_timestamp(
        self, target_usec: int
    ) -> Coroutine[Any, Any, list[TlogEntry]]: ...
    def time_range(self) -> Coroutine[Any, Any, tuple[int, int] | None]: ...

class TlogWriter:
    def __init__(self, path: str) -> None: ...
    def write(self, message: RawMessage) -> int: ...
    def write_entry(self, timestamp_usec: int, message: RawMessage) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> TlogWriter: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: object,
    ) -> None: ...

def validate_plan(plan: MissionPlan) -> list[MissionIssue]: ...
def plans_equivalent(
    lhs: MissionPlan,
    rhs: MissionPlan,
    tolerance: CompareTolerance | None = None,
) -> bool: ...
def normalize_for_compare(plan: MissionPlan) -> MissionPlan: ...
def mission_items_for_upload(plan: MissionPlan) -> list[MissionItem]: ...
def mission_plan_from_download(
    items: list[MissionItem],
) -> MissionPlan: ...
def format_param_file(store: ParamStore) -> str: ...
def parse_param_file(contents: str) -> dict[str, float]: ...
