from collections.abc import Coroutine
from types import TracebackType
from typing import Any, Self

__version__: str

# --- Enums ---

class SystemStatus:
    Unknown: SystemStatus
    Boot: SystemStatus
    Calibrating: SystemStatus
    Standby: SystemStatus
    Active: SystemStatus
    Critical: SystemStatus
    Emergency: SystemStatus
    Poweroff: SystemStatus

class VehicleType:
    Unknown: VehicleType
    FixedWing: VehicleType
    Quadrotor: VehicleType
    Hexarotor: VehicleType
    Octorotor: VehicleType
    Tricopter: VehicleType
    Helicopter: VehicleType
    Coaxial: VehicleType
    GroundRover: VehicleType
    Generic: VehicleType

class AutopilotType:
    Unknown: AutopilotType
    Generic: AutopilotType
    ArduPilotMega: AutopilotType
    Px4: AutopilotType

class GpsFixType:
    NoFix: GpsFixType
    Fix2d: GpsFixType
    Fix3d: GpsFixType
    Dgps: GpsFixType
    RtkFloat: GpsFixType
    RtkFixed: GpsFixType

class MavSeverity:
    Emergency: MavSeverity
    Alert: MavSeverity
    Critical: MavSeverity
    Error: MavSeverity
    Warning: MavSeverity
    Notice: MavSeverity
    Info: MavSeverity
    Debug: MavSeverity

class MissionType:
    Mission: MissionType
    Fence: MissionType
    Rally: MissionType

class MissionFrame:
    Mission: MissionFrame
    GlobalInt: MissionFrame
    GlobalRelativeAltInt: MissionFrame
    GlobalTerrainAltInt: MissionFrame
    LocalNed: MissionFrame
    Other: MissionFrame

class IssueSeverity:
    Error: IssueSeverity
    Warning: IssueSeverity

class TransferDirection:
    Upload: TransferDirection
    Download: TransferDirection

class TransferPhase:
    Idle: TransferPhase
    RequestCount: TransferPhase
    TransferItems: TransferPhase
    AwaitAck: TransferPhase
    Completed: TransferPhase
    Failed: TransferPhase
    Cancelled: TransferPhase

class ParamTransferPhase:
    Idle: ParamTransferPhase
    Downloading: ParamTransferPhase
    Writing: ParamTransferPhase
    Completed: ParamTransferPhase
    Failed: ParamTransferPhase

class ParamType:
    Uint8: ParamType
    Int8: ParamType
    Uint16: ParamType
    Int16: ParamType
    Uint32: ParamType
    Int32: ParamType
    Real32: ParamType

# --- Exception ---

class MavkitError(Exception): ...

# --- State classes ---

class VehicleState:
    @property
    def armed(self) -> bool: ...
    @property
    def custom_mode(self) -> int: ...
    @property
    def mode_name(self) -> str: ...
    @property
    def system_status(self) -> SystemStatus: ...
    @property
    def vehicle_type(self) -> VehicleType: ...
    @property
    def autopilot(self) -> AutopilotType: ...
    @property
    def system_id(self) -> int: ...
    @property
    def component_id(self) -> int: ...
    @property
    def heartbeat_received(self) -> bool: ...

class Telemetry:
    """Aggregated telemetry from all MAVLink message sources.

    Notifies on any field change. For fine-grained subscriptions, use
    per-domain types: Position, Attitude, Battery, Gps, Navigation,
    Terrain, RcChannels via the corresponding Vehicle wait methods.
    """

    @property
    def altitude_m(self) -> float | None: ...
    @property
    def speed_mps(self) -> float | None: ...
    @property
    def heading_deg(self) -> float | None: ...
    @property
    def latitude_deg(self) -> float | None: ...
    @property
    def longitude_deg(self) -> float | None: ...
    @property
    def battery_pct(self) -> float | None: ...
    @property
    def gps_fix_type(self) -> GpsFixType | None: ...
    @property
    def climb_rate_mps(self) -> float | None: ...
    @property
    def throttle_pct(self) -> float | None: ...
    @property
    def airspeed_mps(self) -> float | None: ...
    @property
    def battery_voltage_v(self) -> float | None: ...
    @property
    def battery_current_a(self) -> float | None: ...
    @property
    def gps_satellites(self) -> int | None: ...
    @property
    def gps_hdop(self) -> float | None: ...
    @property
    def roll_deg(self) -> float | None: ...
    @property
    def pitch_deg(self) -> float | None: ...
    @property
    def yaw_deg(self) -> float | None: ...
    @property
    def wp_dist_m(self) -> float | None: ...
    @property
    def nav_bearing_deg(self) -> float | None: ...
    @property
    def target_bearing_deg(self) -> float | None: ...
    @property
    def xtrack_error_m(self) -> float | None: ...
    @property
    def terrain_height_m(self) -> float | None: ...
    @property
    def height_above_terrain_m(self) -> float | None: ...
    @property
    def battery_voltage_cells(self) -> list[float] | None: ...
    @property
    def energy_consumed_wh(self) -> float | None: ...
    @property
    def battery_time_remaining_s(self) -> int | None: ...
    @property
    def rc_channels(self) -> list[int] | None: ...
    @property
    def rc_rssi(self) -> int | None: ...
    @property
    def servo_outputs(self) -> list[int] | None: ...

class Position:
    """Position and velocity data (from VFR_HUD + GLOBAL_POSITION_INT)."""

    @property
    def latitude_deg(self) -> float | None: ...
    @property
    def longitude_deg(self) -> float | None: ...
    @property
    def altitude_m(self) -> float | None: ...
    @property
    def speed_mps(self) -> float | None: ...
    @property
    def airspeed_mps(self) -> float | None: ...
    @property
    def climb_rate_mps(self) -> float | None: ...
    @property
    def heading_deg(self) -> float | None: ...
    @property
    def throttle_pct(self) -> float | None: ...

class Attitude:
    """Vehicle orientation (from ATTITUDE)."""

    @property
    def roll_deg(self) -> float | None: ...
    @property
    def pitch_deg(self) -> float | None: ...
    @property
    def yaw_deg(self) -> float | None: ...

class Battery:
    """Battery power status (from SYS_STATUS + BATTERY_STATUS)."""

    @property
    def remaining_pct(self) -> float | None: ...
    @property
    def voltage_v(self) -> float | None: ...
    @property
    def current_a(self) -> float | None: ...
    @property
    def voltage_cells(self) -> list[float] | None: ...
    @property
    def energy_consumed_wh(self) -> float | None: ...
    @property
    def time_remaining_s(self) -> int | None: ...

class Gps:
    """GPS quality information (from GPS_RAW_INT)."""

    @property
    def fix_type(self) -> GpsFixType | None: ...
    @property
    def satellites(self) -> int | None: ...
    @property
    def hdop(self) -> float | None: ...

class Navigation:
    """Navigation controller output (from NAV_CONTROLLER_OUTPUT)."""

    @property
    def wp_dist_m(self) -> float | None: ...
    @property
    def nav_bearing_deg(self) -> float | None: ...
    @property
    def target_bearing_deg(self) -> float | None: ...
    @property
    def xtrack_error_m(self) -> float | None: ...

class Terrain:
    """Terrain data (from TERRAIN_REPORT)."""

    @property
    def terrain_height_m(self) -> float | None: ...
    @property
    def height_above_terrain_m(self) -> float | None: ...

class RcChannels:
    """RC channels and servo outputs (from RC_CHANNELS + SERVO_OUTPUT_RAW)."""

    @property
    def channels(self) -> list[int] | None: ...
    @property
    def rssi(self) -> int | None: ...
    @property
    def servo_outputs(self) -> list[int] | None: ...

class MissionState:
    @property
    def current_seq(self) -> int: ...
    @property
    def total_items(self) -> int: ...

class LinkState:
    @property
    def kind(self) -> str: ...
    @property
    def message(self) -> str | None: ...

class VehicleIdentity:
    @property
    def system_id(self) -> int: ...
    @property
    def component_id(self) -> int: ...
    @property
    def autopilot(self) -> AutopilotType: ...
    @property
    def vehicle_type(self) -> VehicleType: ...

class FlightMode:
    @property
    def custom_mode(self) -> int: ...
    @property
    def name(self) -> str: ...

class StatusMessage:
    @property
    def text(self) -> str: ...
    @property
    def severity(self) -> MavSeverity: ...

# --- Mission classes ---

class MissionItem:
    def __init__(
        self,
        *,
        seq: int,
        command: int,
        frame: MissionFrame,
        x: int = 0,
        y: int = 0,
        z: float = 0.0,
        param1: float = 0.0,
        param2: float = 0.0,
        param3: float = 0.0,
        param4: float = 0.0,
        current: bool = False,
        autocontinue: bool = True,
    ) -> None: ...
    @property
    def seq(self) -> int: ...
    @property
    def command(self) -> int: ...
    @property
    def frame(self) -> MissionFrame: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def z(self) -> float: ...
    @property
    def param1(self) -> float: ...
    @property
    def param2(self) -> float: ...
    @property
    def param3(self) -> float: ...
    @property
    def param4(self) -> float: ...
    @property
    def current(self) -> bool: ...
    @property
    def autocontinue(self) -> bool: ...

class HomePosition:
    def __init__(
        self,
        *,
        latitude_deg: float,
        longitude_deg: float,
        altitude_m: float = 0.0,
    ) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def altitude_m(self) -> float: ...

class MissionPlan:
    def __init__(
        self,
        *,
        mission_type: MissionType,
        items: list[MissionItem],
        home: HomePosition | None = None,
    ) -> None: ...
    @property
    def mission_type(self) -> MissionType: ...
    @property
    def home(self) -> HomePosition | None: ...
    @property
    def items(self) -> list[MissionItem]: ...
    def __len__(self) -> int: ...

class MissionIssue:
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def seq(self) -> int | None: ...
    @property
    def severity(self) -> IssueSeverity: ...

class TransferProgress:
    @property
    def direction(self) -> TransferDirection: ...
    @property
    def mission_type(self) -> MissionType: ...
    @property
    def phase(self) -> TransferPhase: ...
    @property
    def completed_items(self) -> int: ...
    @property
    def total_items(self) -> int: ...
    @property
    def retries_used(self) -> int: ...

class TransferError:
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...

class RetryPolicy:
    def __init__(
        self,
        *,
        request_timeout_ms: int = 1500,
        item_timeout_ms: int = 250,
        max_retries: int = 5,
    ) -> None: ...
    @property
    def request_timeout_ms(self) -> int: ...
    @property
    def item_timeout_ms(self) -> int: ...
    @property
    def max_retries(self) -> int: ...

class CompareTolerance:
    def __init__(
        self,
        *,
        param_epsilon: float = 0.0001,
        altitude_epsilon_m: float = 0.01,
    ) -> None: ...
    @property
    def param_epsilon(self) -> float: ...
    @property
    def altitude_epsilon_m(self) -> float: ...

# --- Parameter classes ---

class Param:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> float: ...
    @property
    def param_type(self) -> ParamType: ...
    @property
    def index(self) -> int: ...

class ParamStore:
    def __init__(self, *, expected_count: int) -> None: ...
    @property
    def expected_count(self) -> int: ...
    def get(self, name: str) -> Param | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Param]: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Param: ...

class ParamProgress:
    @property
    def phase(self) -> ParamTransferPhase: ...
    @property
    def received(self) -> int: ...
    @property
    def expected(self) -> int: ...

class ParamWriteResult:
    @property
    def name(self) -> str: ...
    @property
    def requested_value(self) -> float: ...
    @property
    def confirmed_value(self) -> float: ...
    @property
    def success(self) -> bool: ...

# --- Config ---

class VehicleConfig:
    def __init__(
        self,
        *,
        gcs_system_id: int = 255,
        gcs_component_id: int = 190,
        auto_request_home: bool = True,
        command_buffer_size: int = 32,
        connect_timeout_secs: float = 30.0,
        retry_policy: RetryPolicy | None = None,
    ) -> None: ...
    @property
    def gcs_system_id(self) -> int: ...
    @property
    def gcs_component_id(self) -> int: ...
    @property
    def auto_request_home(self) -> bool: ...
    @property
    def command_buffer_size(self) -> int: ...
    @property
    def connect_timeout_secs(self) -> float: ...
    @property
    def retry_policy(self) -> RetryPolicy: ...

# --- Vehicle ---

class Vehicle:
    # Connection (async)
    @staticmethod
    def connect(address: str) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_udp(bind_addr: str) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_tcp(addr: str) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_serial(port: str, baud: int) -> Coroutine[Any, Any, Vehicle]: ...
    @staticmethod
    def connect_with_config(
        address: str, config: VehicleConfig
    ) -> Coroutine[Any, Any, Vehicle]: ...

    # State properties (sync)
    @property
    def state(self) -> VehicleState: ...
    @property
    def telemetry(self) -> Telemetry: ...
    @property
    def position(self) -> Position: ...
    @property
    def attitude(self) -> Attitude: ...
    @property
    def battery(self) -> Battery: ...
    @property
    def gps(self) -> Gps: ...
    @property
    def navigation(self) -> Navigation: ...
    @property
    def terrain(self) -> Terrain: ...
    @property
    def rc_channels(self) -> RcChannels: ...
    @property
    def home_position(self) -> HomePosition | None: ...
    @property
    def mission_state(self) -> MissionState: ...
    @property
    def link_state(self) -> LinkState: ...
    @property
    def mission_progress(self) -> TransferProgress | None: ...
    @property
    def param_store(self) -> ParamStore: ...
    @property
    def param_progress(self) -> ParamProgress: ...
    @property
    def statustext(self) -> StatusMessage | None: ...

    # State waiters (async)
    def wait_state(self) -> Coroutine[Any, Any, VehicleState]: ...
    def wait_telemetry(self) -> Coroutine[Any, Any, Telemetry]: ...
    def wait_position(self) -> Coroutine[Any, Any, Position]: ...
    def wait_attitude(self) -> Coroutine[Any, Any, Attitude]: ...
    def wait_battery(self) -> Coroutine[Any, Any, Battery]: ...
    def wait_gps(self) -> Coroutine[Any, Any, Gps]: ...
    def wait_navigation(self) -> Coroutine[Any, Any, Navigation]: ...
    def wait_terrain(self) -> Coroutine[Any, Any, Terrain]: ...
    def wait_rc_channels(self) -> Coroutine[Any, Any, RcChannels]: ...
    def wait_home_position(self) -> Coroutine[Any, Any, HomePosition | None]: ...
    def wait_mission_state(self) -> Coroutine[Any, Any, MissionState]: ...
    def wait_link_state(self) -> Coroutine[Any, Any, LinkState]: ...
    def wait_mission_progress(self) -> Coroutine[Any, Any, TransferProgress | None]: ...
    def wait_param_store(self) -> Coroutine[Any, Any, ParamStore]: ...
    def wait_param_progress(self) -> Coroutine[Any, Any, ParamProgress]: ...
    def wait_statustext(self) -> Coroutine[Any, Any, StatusMessage | None]: ...
    def subscribe_raw_messages(self) -> RawMessageStream: ...

    # Vehicle commands (async)
    def arm(self, force: bool) -> Coroutine[Any, Any, None]: ...
    def disarm(self, force: bool) -> Coroutine[Any, Any, None]: ...
    def set_mode(self, custom_mode: int) -> Coroutine[Any, Any, None]: ...
    def set_mode_by_name(self, name: str) -> Coroutine[Any, Any, None]: ...
    def takeoff(self, altitude_m: float) -> Coroutine[Any, Any, None]: ...
    def goto(
        self, lat_deg: float, lon_deg: float, alt_m: float
    ) -> Coroutine[Any, Any, None]: ...
    def command_long(
        self,
        command_id: int,
        param1: float = 0.0,
        param2: float = 0.0,
        param3: float = 0.0,
        param4: float = 0.0,
        param5: float = 0.0,
        param6: float = 0.0,
        param7: float = 0.0,
    ) -> Coroutine[Any, Any, None]: ...
    def preflight_calibration(
        self, gyro: bool, accel: bool, radio_trim: bool
    ) -> Coroutine[Any, Any, None]: ...
    def reboot_to_bootloader(self) -> Coroutine[Any, Any, None]: ...
    def disconnect(self) -> Coroutine[Any, Any, None]: ...

    # Mission operations (async)
    def upload_mission(self, plan: MissionPlan) -> Coroutine[Any, Any, None]: ...
    def download_mission(
        self, mission_type: MissionType
    ) -> Coroutine[Any, Any, MissionPlan]: ...
    def clear_mission(self, mission_type: MissionType) -> Coroutine[Any, Any, None]: ...
    def verify_mission_roundtrip(
        self, plan: MissionPlan
    ) -> Coroutine[Any, Any, bool]: ...
    def set_current_mission_item(self, seq: int) -> Coroutine[Any, Any, None]: ...

    # Parameter operations (async)
    def download_params(self) -> Coroutine[Any, Any, ParamStore]: ...
    def write_param(self, name: str, value: float) -> Coroutine[Any, Any, Param]: ...
    def write_params_batch(
        self, params: list[tuple[str, float]]
    ) -> Coroutine[Any, Any, list[ParamWriteResult]]: ...

    # Async context manager
    def __aenter__(self) -> Coroutine[Any, Any, Self]: ...
    def __aexit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: TracebackType | None = None,
    ) -> Coroutine[Any, Any, bool]: ...

    # Sync methods
    def available_modes(self) -> list[FlightMode]: ...
    def identity(self) -> VehicleIdentity | None: ...
    def cancel_mission_transfer(self) -> None: ...

# --- Raw message classes ---

class RawMessage:
    """A single raw MAVLink message with header metadata."""

    @property
    def system_id(self) -> int: ...
    @property
    def component_id(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def message_id(self) -> int: ...
    @property
    def message_name(self) -> str: ...
    def message_json(self) -> str: ...

class RawMessageStream:
    """Async stream of raw MAVLink messages from a Vehicle connection."""

    def recv(self) -> Coroutine[Any, Any, RawMessage]: ...

# --- Tlog classes ---

class TlogEntry:
    @property
    def timestamp_usec(self) -> int: ...
    @property
    def message_id(self) -> int: ...
    @property
    def message_name(self) -> str: ...
    def message_json(self) -> str: ...

class TlogFile:
    @staticmethod
    def open(path: str) -> Coroutine[Any, Any, TlogFile]: ...
    def entries(self) -> Coroutine[Any, Any, list[TlogEntry]]: ...
    def seek_to_timestamp(
        self, target_usec: int
    ) -> Coroutine[Any, Any, list[TlogEntry]]: ...
    def time_range(self) -> Coroutine[Any, Any, tuple[int, int] | None]: ...

# --- Free functions ---

def validate_plan(plan: MissionPlan) -> list[MissionIssue]: ...
def plans_equivalent(
    lhs: MissionPlan,
    rhs: MissionPlan,
    tolerance: CompareTolerance | None = None,
) -> bool: ...
def normalize_for_compare(plan: MissionPlan) -> MissionPlan: ...
def items_for_wire_upload(plan: MissionPlan) -> list[MissionItem]: ...
def plan_from_wire_download(
    mission_type: MissionType, items: list[MissionItem]
) -> MissionPlan: ...
def format_param_file(store: ParamStore) -> str: ...
def parse_param_file(contents: str) -> dict[str, float]: ...
